feat(CircleCiBadge): add new CircleCI badge
dbartholomae/jsx-readme pull request #23
Opened 2020-09-30 12:11 UTC by i-am-jeetu

Closes #2 

## Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

Hi, I have a doubt, since this repo isn't using CircleCI, So I didn't feel the need to edit Readmes. Is this correct?

2020-09-30 12:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dbartholomae/jsx-readme?pullRequest=23) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dbartholomae/jsx-readme?pullRequest=23) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dbartholomae/jsx-readme?pullRequest=23) it.</sub>

2020-09-30 12:16 UTC, i-am-jeetu commented
Hi @dbartholomae , Please guide me to resolve the merge conflict. 
And since this repo is not using CircleCI. So, I didn't edit Readmes (as being done by other PRs adding new badges). Is it fine?

2020-09-30 16:55 UTC, dbartholomae requested changes
I've resolved the merge conflict and added some comments on the code :)

2020-09-30 16:55 UTC, dbartholomae commented on src/components/badges/CircleCIBadge.tsx
> +  style?: string;
Please type correctly as `"svg" | "shield"` instead of `string`

2020-09-30 16:55 UTC, dbartholomae commented on src/components/badges/CircleCIBadge.tsx
> +  }
Please remove this check after adding the type above

2020-09-30 16:55 UTC, dbartholomae commented on src/components/badges/CircleCIBadge.tsx
> +  if (branch === undefined) {
This if/else can be simplified by using a ternay operator in lines 32/33 (see below)

2020-09-30 16:55 UTC, dbartholomae commented on src/components/badges/CircleCIBadge.tsx
> +  if (branch === undefined) {
Actually, nevermind, I like this version better

2020-09-30 16:55 UTC, dbartholomae commented on src/components/badges/CircleCIBadge.tsx
> +        {repo}
Instead, this should be `CircleCI`, the same in line 44.

2020-09-30 17:21 UTC, dbartholomae commented
Thanks! Could you squash down into one commit? Each commit with `feat:` will create a line in the changelog, so having to commits will create the same entry twice.

2020-09-30 17:53 UTC, i-am-jeetu commented
Hi @dbartholomae, Sorry I am new to this. Can you please guide me how to squash two commits to one. Sorry for disturbing 😅 
Looks like I messed it all up

2020-09-30 17:55 UTC, dbartholomae commented
No worries! I'm always happy to help, and the goal here is specifically to make learning easier :)
I'm currently not at home but will provide you with more details when I am.

2020-09-30 17:59 UTC, dbartholomae commented
Are you using an IDE like VSCode to commit and push, or do you type them commands into the terminal (`git commit`...)?

2020-09-30 18:17 UTC, i-am-jeetu commented
I type git commit

2020-09-30 18:28 UTC, dbartholomae commented
Ok, will write more when I'm home :)

2020-09-30 18:48 UTC, i-am-jeetu commented
![image](https://user-images.githubusercontent.com/66921514/94726745-4b0dfa00-037b-11eb-9ba6-4474fc20abd8.png)

Shoud I add drop to all the commits from b6318fe to 55a0f83? I think it will work :)

2020-09-30 18:59 UTC, dbartholomae commented
These commits are already in the published version and not part of the PR, so it is best not to touch them. They would be added again when merging the branch onto the main branch.
You can checkout the main branch (or even look at it on GitHub) to see the which commits already are on main.

2020-09-30 20:00 UTC, i-am-jeetu commented
Hello again @dbartholomae, Looks like I finally understood branching, rebaseing and commit graphs and managed to make the PR right. Please have a look :)

2020-10-01 08:18 UTC, dbartholomae approved these changes

2020-10-01 08:19 UTC, merged

2020-10-01 08:19 UTC, dbartholomae commented
Thanks! Perfect! If you have any questions on the rebasing, specifically for example why I prefer to do it like this, just let me know :)

2020-10-01 09:54 UTC, i-am-jeetu commented
Thanks @dbartholomae, It was a great learning experience and a pleasure interacting with you. I will ping you here (or on Hacktoberfest's Discord) if I struggle again with git.  :blush: