feat(CoverallsBadge): add badge and test
dbartholomae/jsx-readme pull request #46
Opened 2020-10-16 07:07 UTC by MDShields7

Closes #3 
## Checklist:
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

2020-10-16 07:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dbartholomae/jsx-readme?pullRequest=46) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dbartholomae/jsx-readme?pullRequest=46) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dbartholomae/jsx-readme?pullRequest=46) it.</sub>

2020-10-16 07:29 UTC, MDShields7 commented
I had these errors earlier locally, which stem from my labelling a file as Javascript. I accidentally named the file 'CoverallsBadge.js' to start, and later changed it to 'CoverallsBadge.tsx'. However, the CoverallsBadge.test.tsx was still importing from "./CoverallsBadge" (CoverallsBadge being a .js file in its mind).
I fixed this issue locally, and my pre-commit tests passed, but it seems the error has travelled to the build somehow. Since my local version seems fine, I am not sure how to fix this, except by trial and error.
Do you have a suggestion?

2020-10-16 11:51 UTC, dbartholomae commented
Thanks! In the commit there is a file "src/components/badges/CoverallsBadge.js" which should be called " src/components/badges/CoverallsBadge.tsx"

2020-10-18 17:57 UTC, dbartholomae requested changes
PR looks mostly fine. One small stylistic change, and you'll have to export the badge from the barrel file src/components/badges/index.ts so that it can be used.

2020-10-18 17:57 UTC, dbartholomae commented on src/components/badges/CoverallsBadge.tsx
> +  } else {
No need for the `else` :)

2020-11-09 18:31 UTC, dbartholomae approved these changes

2020-11-09 18:31 UTC, merged

2020-11-09 18:32 UTC, dbartholomae commented
Thanks, looks great! :)